### ISSUE TITLE
Rename the app "Website" to "WebsiteEditor"

### ISSUE THREAD

**Issue by tomalec** [StarcounterApps/Website#34]
As an extension to https://github.com/StarcounterPrefabs/Website/issues/15
what about renaming this app to something like "Blender"?

As it fact this is the app that lets you blend the output of many apps which is just hidden behind inaccessible URLs.

//cc @warpech

**Comment by tomalec** [comment]
Or at least call the suite: 
 - Website
 - WebsiteProvider
 - CompositionProvider
 - CompositionEditor

the "Blending Suite"

**Comment by warpech** [comment]
Good initiative, let's sleep on it. 

An idea to ridiculous to consider, but to funny to keep to myself: **Blend-a-web**

![image](https://cloud.githubusercontent.com/assets/566463/22985800/e754b420-f3a9-11e6-8833-106b7535da36.png)

**Comment by warpech** [comment]
Let's discuss that on Monday.

**Comment by tomalec** [comment]
Blending Scaffold?

**Comment by warpech** [comment]
It turns out that the name "Website" has sticked to us and it is not that much inaccurate, so generally speaking I think we should keep it.

But, since we have the following apps in the blending suite:

- Website
- WebsiteProvider
- CompositionProvider
- CompositionEditor

I think that it makes huge sense to rename *Website* to *WebsiteEditor*

**Comment by bouguila** [comment]
closing as done.
