### ISSUE TITLE
Incorrect merging of JSON when adding another app's data into the same Section

### ISSUE THREAD

**Issue by un-tone** [StarcounterApps/Website#63]
### Steps to reproduce
1. Start Website (branch `develop`), WebsiteProvider (branch `develop`), SignIn (branch `develop`)
2. Start People (branch `develop`) and KitchenSink (branch `test/External-App-Link-People`)
3. Go to `http://localhost:8080/KitchenSink`
4. Click on the "People app" link (below in the navigation area)
5. Check Console logs and Network tabs

### Expected result
Shows the Persons page of the People app

### Actual result
Throws an error `Uncaught TypeError: Cannot read property 'CurrentPage' of undefined`.
The `WebsiteProvider` should send in the response a correct `add` operation data for the People app data and a `remove` operation for KitchenSink data.

##### Involved apps' version
 - StarcounterApps/Website@04fd00046e025d618fdbf89c211b28bc54f4d0dd
 - StarcounterApps/KitchenSink@fae9156da92173ab3f70d79bed38d5dcb254d149
 
##### Browsers affected

- [x] Chrome

### Screenshot
![image](https://cloud.githubusercontent.com/assets/1625378/23853382/5a1d767e-07fd-11e7-959a-c695694e23ae.png)

**Comment by warpech** [comment]
@chrhol could you pls investigate this? Looks like a server side issue with patch generation.

**Comment by chrhol** [comment]
I've found a couple of bugs. One I have fixed (only locally so far though). The other one comes from reusing the instance of the sections, where patches for the new and removed siblings is not detected. This I have yet to fix. I will create an issue in the Starcounter repo for that one.

I found one more thing, I tried to change so that the section is not reused (as a workaround) but instead always sends out a replace of the whole row, by commenting out [these lines](https://github.com/StarcounterApps/Website/blob/develop/src/WebsiteProvider/Api/ContentHandlers.cs#L208-L209)

The patches looks correct, however the viewmodel doesn't seem to be updated. For this one I have no idea why, there's nothing in the console. The patch just dont get applied.
![patch](https://cloud.githubusercontent.com/assets/1658979/24113417/0721ef72-0d9d-11e7-931a-294b9fb472be.PNG)
![model](https://cloud.githubusercontent.com/assets/1658979/24113419/0ac6a14a-0d9d-11e7-9cfc-0d55f9d75f85.PNG)

**Comment by chrhol** [comment]
I think I have found the problems. Still not pushed though. I need to test it some more before pushing, I'm aiming at having it pushed before the next nightly build though.

Issue in Starcounter: https://github.com/Starcounter/Starcounter/issues/4170

**Comment by chrhol** [comment]
I've pushed the fixes for the incorrect/missing patches now. Should be included in this nights nightly build. Please let me know if this solves this issue.

**Comment by un-tone** [comment]
The issue was fixed. Thanks @chrhol

**Comment by warpech** [comment]
Thank you both! 🎊
