### ISSUE TITLE
Apply BEM to Website's private CSS

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/Website#9]
This app contains globally applied CSS rules in stylesheets: https://github.com/StarcounterSamples/Website/search?utf8=%E2%9C%93&q=filename%3A.css

All private CSS should be converted to BEM-style CSS classes defined in a stylesheet, according to the intent started in the issue https://github.com/Starcounter/Starcounter/issues/3450 and explained in the article http://starcounter.io/guides/web/avoiding-css-conflicts/

**Comment by diliger** [comment]
What are these styles for?
![image](https://cloud.githubusercontent.com/assets/15857369/24334961/1839a0cc-127d-11e7-8d57-31d892311405.png)

Should they be bemified?
And what means `/*shimmed browsers*/`?

**Comment by warpech** [comment]
@tomalec could you please prepare some response in form of a quick blog post?

**Comment by tomalec** [comment]
To be honest I would say those selectors are buggy.
1. `h1` is matching entire document, not just "shimmy-distributed" ones.
2. ekhm.. https://github.com/Starcounter/RebelsLounge/issues/66

Do we really want to post a blog entry on the fact that WebComponents polyfill v0 (which we are going to change ASAP) is limited https://github.com/webcomponents/webcomponentsjs/tree/v0#limited-css-encapsulation- and buggy (that's why v1 is there)? We were just applying workarounds on workaround, and we give up in fixing the real cause of this particular bug in polyfill? And we cannot affort to adapt to v1 soon enough?

Personally, I don't think it's beneficiary to advertise hacks and workarounds, as they might stay longer than the need for them and may stay with us even in v1. Plus they are unstable, and may change in any moment (as everything that relies on bugs)

**Comment by tomalec** [comment]
Maybe instead of a blog post for this particular workaround, we should prepare a cheat-sheet with common Shadow DOM snippets, selectors, use-cases, tricks, which will also cover know bugs, limitation etc. I think it may be easier to maintain it in such form, and it should give more value to the team.

**Comment by warpech** [comment]
Cheat-sheet is a very good idea. We and our partners have 20-30 apps to migrate, so it will not be a waste of time.

**Comment by diliger** [comment]
So, how to deal with it here?

**Comment by warpech** [comment]
Only BEMify the styles in https://github.com/StarcounterApps/Website/blob/develop/src/Website/wwwroot/Website/css/standalone.css

Regarding the file https://github.com/StarcounterApps/Website/blob/develop/src/Website/wwwroot/Website/css/AppHub.css, it shows an attempt to style the distributed DOM, which is something that we should solve separately from this issue. Disregard that file for now.

**Comment by warpech** [comment]
Ping @diliger

**Comment by warpech** [comment]
Fixed in #9
